baseURL = 'https://example.org/'
languageCode = 'pt-br'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Sobre Nós'
pageRef = '/sobrenos'
weight = 10

[[menus.main]]
name = 'Serviços'
pageRef = '/servicos'
weight = 20

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 30

[[menus.main]]
name = 'Entre em Contato'
pageRef = '/contato'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
